name: Deploy to Firebase

on:
  workflow_run:
    workflows: ["Run Tests"]  # This should match the name of the test workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Ensure deployment only happens if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Authenticate with Firebase
        run: firebase use --add

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
