name: Commit Linter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt  # Modify if your linter doesn’t need dependencies

      - name: Run commit linter
        run: cd src && python main.py  # Replace with your actual script
