name: Test & Deploy

on:
  push:
    branches:
      - main   # Trigger on push to main
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  # Setup job
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Test job
  test:
    runs-on: ubuntu-latest
    needs: setup  # Ensure setup job runs first
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run tests
        run: |
          pytest

  # Deploy job (runs only if the tests pass)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests run first and pass
    if: success()  # Only run this job if the test job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Authenticate with Firebase using token
        run: |
          firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Functions
        run: |
          firebase deploy --only functions  # Change to deploy functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
